### PR TITLE
Executive.list> handle one executive having multiple positions

### LINKED ISSUE #85: Executive.list breaks when faced with multiple positions for one exec
In Northern Ireland, we — rightly or wrongly — pick up two HoG positions, the First Minister and the Deputy First Minister. This leads to `Executive.list` creating a new `Executive` for each and then trying to order them. As the `Executive#executive_item_id` is the same, it tries to order the positions, which are incomparable.

https://github.com/everypolitician/commons-builder/blob/40886d43d4096c2eed4c55a35b0012b478b102e3/lib/commons/builder/executive.rb#L63

Note: It's not enough to just implement `Position#<=>`, as it would still be returning duplicate `Executive`s, when there should be one `Executive` with multiple positions.

### PR DESCRIPTION
**Pull request by alexsdutton**
Previously this would attempt to create a new Executive object per
position and then fail to sort them. This now groups all positions for a
given executive into the same Executive object.

Closes #85.

### CODE REVIEW

File: test/commons/builder/executive_test.rb [hunk 1]
```diff
@@ -51,4 +51,18 @@ def test_list_with_missing_position
     executives = Executive.list(config)
     assert_equal [], executives
   end
+
+  def test_list_with_two_positions_for_one_executive
+    # If an executive is listed in the results more than once, with multiple positions, group those positions into a
+    # single executive entry. Also ensure that the entries are sorted by executive and position item IDs.
+    stub_request(:post, 'https://query.wikidata.org/sparql')
+      .to_return(body: open('test/fixtures/executive-index-two-positions.srj', 'r')).then
+      .to_return(body: '[]')
```
Comment (mhl) [inline test/commons/builder/executive_test.rb]: I think the second `.then.to_return` is unnecessary here (the test pass without it).
